id: P006794
initial_creation_type: ocr
source_metadata:
  id: bdr:W237
  title: མངོན་པ་མཛོད་ཀྱི་རྣམ་བཤད
  author: ''
  volumes:
    cf08aee9102f4e8eb13db8d2005a3e11:
      image_group_id: I1KG799
      title: ''
      volume_number: 1
      total_pages: 416
      base_file: v001.txt
