id: I434EBF9D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T00:15:06+00:00'
last_modified: '2022-06-08T06:54:19.999906+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W237
  title: མངོན་པ་མཛོད་ཀྱི་རྣམ་བཤད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DFC8:
      image_group_id: I1KG799
      title: ''
      total_pages: 416
      order: 1
      base_file: DFC8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
