id: I434EBF9D
legacy_id: P006794
ocr_import_info:
  bdrc_scan_id: W237
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T00:12:23'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T02:11:20.754971+00:00'
last_modified: 2022-09-02 10:11:49.416200
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W237
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW237
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མངོན་པ་མཛོད་ཀྱི་རྣམ་བཤད།
  author: ཏཱ་ལའི་བླ་མ ༠༥་ངག་དབང་བློ་བཟང་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.6794272408621329
  ocr_word_median_confidence_index: 0.7699999809265137
quality: null
bases:
  I1KG799:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG799
      total_pages: 416
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG799.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.6794272408621329
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
